config_version: 3.27

'comment0': 'Language: zh_cn(简体中文), en_us(English)'
language: en_us

'comment52': 'if enable PRO version'
enable_pro: false

'comment53': 'PRO version registered username (You cannot change it after registration)'
pro_name: xxxxxxxxxxxxxx

'comment54': 'PRO version registered password'
pro_password: xxxxxxxxxxxxxx

'comment1': 'set true to use mysql database, set false to use YAML store data'
enableDataBase: false

'comment2': 'fill with your Host, default is Localhost'
host: localhost
'comment3': 'fill with your Mysql port, default is 3306'
port: 3306
'comment4': 'fill with your username, default is root'
username: root
'comment5': 'fill with your password'
password: root
'comment6': 'fill with the database you want to connect to'
database: minecraft

'comment25': 'enable sidebar'
enable_scoreboard: true

'comment21': 'if enable auto version check'
enable_version_check: true

'comment56': 'if enable auto upgrade (you must also enable auto version check)'
enable_auto_update: false

'comment22': 'if enable Home function'
enable_home: true

'comment34': 'if enable Chest Lock function'
enable_lock: true

'comment33': 'if enable Email function'
enable_email: true

'comment32': 'if enable Join Welcome function'
enable_onjoin: true

'comment35': 'if enable Remote Bag function'
enable_remote_chest: true

'comment36': 'if enable sidebar display armor durability function（if performs bad please close this function）'
enable_armor_check: true

'comment37': 'if enable multi-worlds manage/teleport'
enable_multiworlds: true

'comment39': 'if enable chat prefix function'
enable_chat: true

'comment40': 'if enable chat color function'
enable_chat_color: true

'comment41': 'if enable chat @ function'
enable_chat_att: true

'comment9': 'enable whitelist'
enable_white_list: false

'comment43': 'enable above-head prefix suffix display '
enable_name_prefix: true

'comment46': 'if enable Login function'
enable_login: true

'comment47': 'if enable Kits function'
enable_kits: true

'comment55': 'if enable Cleaner function'
enable_cleaner: true

'comment12': 'enable PAPI'
enable_PAPI: true

'comment13': 'enable Death Punishment function'
enable_death_punishment: true

'comment14': 'enable social system'
enable_social_system: true

'comment15': 'enable tpa function'
enable_tpa: true

'comment16': 'enable tpa function'
enable_warp: true

'comment17': 'enable back function'
enable_back: true

'comment18': 'enable spawn function'
enable_spawn: true

'comment19': 'enable auto-reply function'
enable_auto-reply: true

'comment20': 'enable random_tp function'
enable_random_tp: true

'comment23': 'enable fly_command function'
enable_fly_command: true

'comment24': 'enable tpback_command function'
enable_tpback_command: true

'comment26': 'enable first_join_broadcast function'
enable_first_join_broadcast: true

'comment27': 'enable lobby&setlobby commands'
enable_lobby_command: true

'comment28': 'enable invsee command'
enable_invsee_command: true

'comment29': 'enable enderChest_see command'
enable_enderChest_see_command: true

'comment42': 'customize above-head display prefix'
name_prefix: '§e[§dLv.%player_level%§e]'

'comment44': 'customize above-head display suffix'
name_suffix: '§e[§c%player_health_rounded%§e/§c%player_max_health_rounded%§e]'